# Generated by Django 4.2.19 on 2025-05-22 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatHistory',
            fields=[
                ('chatId', models.AutoField(primary_key=True, serialize=False)),
                ('chat_heading', models.CharField(max_length=150)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('userId', models.AutoField(primary_key=True, serialize=False)),
                ('userEmail', models.EmailField(max_length=150, unique=True)),
                ('userPassword', models.CharField(max_length=150)),
                ('userType', models.CharField(choices=[('admin', 'Admin'), ('student', 'Student'), ('teacher', 'Teacher'), ('not student', 'Not Student')], default='not student', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='starredChat',
            fields=[
                ('starredId', models.AutoField(primary_key=True, serialize=False)),
                ('is_starred', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('chatId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='starred_chats', to='frontend.chathistory')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='starred_chats', to='frontend.user')),
            ],
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('messageId', models.AutoField(primary_key=True, serialize=False)),
                ('input_query', models.TextField()),
                ('bot_response', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('chatId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='frontend.chathistory')),
            ],
        ),
        migrations.AddField(
            model_name='chathistory',
            name='userId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_histories', to='frontend.user'),
        ),
        migrations.CreateModel(
            name='ChatFeedback',
            fields=[
                ('feedbackId', models.AutoField(primary_key=True, serialize=False)),
                ('messageFeed', models.CharField(blank=True, choices=[('like', 'Like'), ('dislike', 'Dislike')], default=None, max_length=8, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('messageId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='frontend.chatmessage')),
            ],
        ),
    ]
